### ISSUE TITLE
Range Queries using Segment Tree | C++ 

### ISSUE THREAD

**Issue by arnabsen1729** [amritansh22/Data-Structures-and-Algorithms-in-cpp#100]
### Descp: 
Range Queries involves operation on a range of values in an array, operations can be Sum, Max, Min. and also Update. To solve this, many Data Structures are available, Segment Tree is one of them. 

### Type of issue:

- [ ]  Add code
- [ ]  Add comments and documentation for easier understanding

### Language

- [ ]  C++

### Tasks
- [x]  Star the repo
- [ ]  Fork the repo
- [ ]  Create a pull request

@amritansh22  Can you assign this issue to me, I would love to contribute :smile:

**Comment by arnabsen1729** [comment]
@amritansh22 Sorry to bother you again, but can you also add the labels of Hacktoberfest here as well. Also one thing, when I will be sending the PR from the forked repo, shall I mention this issue ? I should r8?
