### ISSUE TITLE
Range Queries using Fenwick Tree

### ISSUE THREAD

**Issue by arnabsen1729** [amritansh22/Data-Structures-and-Algorithms-in-cpp#101]
### Descp: 
Range Queries involves operation on a range of values in an array, operations can be Sum, Max, Min. and also Update. To solve this, many Data Structures are available, Fenwick tree has an easier implementation and is thus very helpful in coding competitions. But it is not as flexible as Segment tree

### Type of issue:

- [ ]  Add code
- [ ]  Add comments and documentation for easier understanding

### Language

- [ ]  C++

### Tasks
- [x]  Star the repo
- [ ]  Fork the repo
- [ ]  Create a pull request

@amritansh22  Can you assign this issue to me, I would love to contribute :smile:

**Comment by amritansh22** [comment]
@arnabsen1729 Done

**Comment by amritansh22** [comment]
@arnabsen1729 Done
