### ISSUE TITLE
Minimum Time Visiting All The Points On A Cartesian Plane

### ISSUE THREAD

**Issue by nischalsoni** [amritansh22/Data-Structures-and-Algorithms-in-cpp#111]
### Finding minimum time visiting all the points on a cartesian plane ###

**Description:**
On a plane there are `n` points with integer coordinates `points[i] = [xi, yi]`. Your task is to find the minimum time in seconds to visit all points.

You can move according to the next rules:

- In one second always you can either move vertically, horizontally by one unit or diagonally (it means to move one unit vertically and one unit horizontally in one second).

- You have to visit the points in the same order as they appear in the array.

**Type of Issue:**
- [x] Adding a code

**Language:**
- [x] C++

**Tasks:**

- [x] Star the repository
- [x] Fork the repository
- [x] Create a pull request once done.

**Comment by nischalsoni** [comment]
@amritansh22 please assign.

**Comment by amritansh22** [comment]
@nischalsoni Done
