### ISSUE TITLE
Prefix Sum and finding sum of range. 

### ISSUE THREAD

**Issue by arnabsen1729** [amritansh22/Data-Structures-and-Algorithms-in-cpp#182]
### Type of issue:

- [ ]  Add code
- [ ]  Add comments and documentation for easier understanding

### Language

- [ ]  C++

### Tasks
- [x]  Star the repo
- [ ]  Fork the repo
- [ ]  Create a pull request

@amritansh22  Can you assign this issue to me, I would love to contribute :smile:

**Comment by d2Anubis** [comment]
I want to work on this.

**Comment by amritansh22** [comment]
Yes sure. I have assigned the issue to you

**Comment by aryanchauhan21** [comment]
Can I start working on this issue and make a pull request ?

**Comment by arnabsen1729** [comment]
@aryanchauhan21 yes sure, make sure you follow the guidelines
