### ISSUE TITLE
Lowest Common Ancestor using Binary Lifting

### ISSUE THREAD

**Issue by arnabsen1729** [amritansh22/Data-Structures-and-Algorithms-in-cpp#186]
### Type of issue:

- [ ]  Add code
- [ ]  Add comments and documentation for easier understanding

### Language

- [ ]  C++

### Tasks
- [x]  Star the repo
- [x]  Fork the repo
- [ ]  Create a pull request

@amritansh22  Can you assign this issue to me, I would love to contribute :smile:

**Comment by arnabsen1729** [comment]
@amritansh22 also can you add the labels of Hacktoberfest

**Comment by amritansh22** [comment]
Sorry but there is already an existing PR. You may try highest common ancestor
