### ISSUE TITLE
Steps By Knight

### ISSUE THREAD

**Issue by 0ChanAk** [amritansh22/Data-Structures-and-Algorithms-in-cpp#468]
**Title: Steps By Knight**

**Type of issue:**
 Add code
 Add comments and documentation for easier understanding

**Language**
 C++

**Tasks**
 

- [ ]   Star the repo

 

- [ ] Fork the repo

- [ ]  Create a pull request

@amritansh22 Can you assign this issue to me, I want to contribute 😄
