### ISSUE TITLE
 Find how many numbers are smaller than any number in an array

### ISSUE THREAD

**Issue by nischalsoni** [amritansh22/Data-Structures-and-Algorithms-in-cpp#99]
### Finding how many numbers are smaller than any number in an array ###

**Description:**
Given the array nums, for each `nums[i]` find out how many numbers in the array are smaller than it. That is, for each `nums[i]` you have to count the number of valid `j's` such that `j != i` and `nums[j] < nums[i]`.
Return the answer in an array.

**Type of Issue:**
- [x] Add code

**Language:**
- [x] C++

**Tasks:**

- [x] Star the repository
- [x] Fork the repository
- [x] Create a pull request once done.

**Comment by nischalsoni** [comment]
Can i do this?

**Comment by amritansh22** [comment]
Yes sure. Assigned it to you.

**Comment by pAnKAjDWivEdII** [comment]
can i do this ??

**Comment by amritansh22** [comment]
@pAnKAjDWivEdII This issue is already assigned. You can look for other issues or create your own.

**Comment by piyush9311** [comment]
May I work on this issue

**Comment by amritansh22** [comment]
@piyush9311 This issue is already assigned. You may look for some other or open your own issues here
